Attribute VB_Name = "MPrinter"
Option Explicit

Public Enum PaperKind
    Custom = 0                              ' Das Papierformat wird vom Benutzer festgelegt.
    Letter = 1                              ' Letter paper (8.5 in.by 11 in.).
    LetterSmall = 2                         ' Letter small paper (8.5 in.by 11 in.).
    Tabloid = 3                             ' Tabloid paper (11 in.by 17 in.).
    Ledger = 4                              ' Ledger paper (17 in.by 11 in.).
    Legal = 5                               ' Legal paper (8.5 in.by 14 in.).
    Statement = 6                           ' Statement paper (5.5 in.by 8.5 in.).
    Executive = 7                           ' Executive paper (7.25 in.by 10.5 in.).
    DIN_A3 = 8                              ' A3 paper (297 mm by 420 mm).
    DIN_A4 = 9                              ' A4 (210 x 297 mm).
    DIN_A4Small = 10                        ' A4 klein (210 x 297 mm).
    DIN_A5 = 11                             ' A5 (148 x 210 mm).
    DIN_B4 = 12                             ' B4 (250 x 353 mm).
    DIN_B5 = 13                             ' B5 (176 x 250 mm).
    Folio = 14                              ' Folio paper (8.5 in.by 13 in.).
    Quarto = 15                             ' Quarto (215 x 275 mm).
    Standard10x14 = 16                      ' Standard paper (10 in.by 14 in.).
    Standard11x17 = 17                      ' Standard paper (11 in.by 17 in.).
    Note = 18                               ' Note paper (8.5 in.by 11 in.).
    Number9Envelope = 19                    ' #9 envelope (3.875 in.by 8.875 in.).
    Number10Envelope = 20                   ' #10 envelope (4.125 in.by 9.5 in.).
    Number11Envelope = 21                   ' #11 envelope (4.5 in.by 10.375 in.).
    Number12Envelope = 22                   ' #12 envelope (4.75 in.by 11 in.).
    Number14Envelope = 23                   ' #14 envelope (5 in.by 11.5 in.).
    CSheet = 24                             ' C paper (17 in.by 22 in.).
    DSheet = 25                             ' D paper (22 in.by 34 in.).
    ESheet = 26                             ' E paper (34 in.by 44 in.).
    DLEnvelope = 27                         ' Umschlag DL (110 x 220 mm).
    C5Envelope = 28                         ' Umschlag C5 (162 x 229 mm).
    C3Envelope = 29                         ' Umschlag C3 (324 x 458 mm).
    C4Envelope = 30                         ' Umschlag C4 (229 x 324 mm).
    C6Envelope = 31                         ' C6 envelope (114 mm by 162 mm).
    C65Envelope = 32                        ' C65 envelope (114 mm by 229 mm).
    B4Envelope = 33                         ' B4 (250 x 353 mm).
    B5Envelope = 34                         ' Umschlag B5 (176 x 250 mm).
    B6Envelope = 35                         ' Umschlag B6 (176 x 125 mm).
    ItalyEnvelope = 36                      ' Umschlag Italien (110 x 230 mm).
    MonarchEnvelope = 37                    ' Monarch envelope (3.875 in.by 7.5 in.).
    PersonalEnvelope = 38                   ' 6 3/4 envelope (3.625 in.by 6.5 in.).
    USStandardFanfold = 39                  ' US standard fanfold (14.875 in.by 11 in.).
    GermanStandardFanfold = 40              ' German standard fanfold (8.5 in.by 12 in.).
    GermanLegalFanfold = 41                 ' German legal fanfold (8.5 in.by 13 in.).
    IsoB4 = 42                              ' B4 (ISO) (250 x 353 mm).
    JapanesePostcard = 43                   ' Japanische Postkarte (100 x 148 mm).
    Standard9x11 = 44                       ' Standard paper (9 in.by 11 in.).
    Standard10x11 = 45                      ' Standard paper (10 in.by 11 in.).
    Standard15x11 = 46                      ' Standard paper (15 in.by 11 in.).
    InviteEnvelope = 47                     ' Einladungsumschlag (220 x 220 mm).
    '? = 48
    '? = 49
    LetterExtra = 50                        ' Letter extra paper (9.275 in.by 12 in.).Dieser Wert ist PostScript-Treiber-spezifisch und wird ausschließlich von Linotronic-Druckern zur Senkung des Papierverbrauchs verwendet.
    LegalExtra = 51                         ' Legal extra paper (9.275 in.by 15 in.).Dieser Wert ist PostScript-Treiber-spezifisch und wird ausschließlich von Linotronic-Druckern zur Senkung des Papierverbrauchs verwendet.
    TabloidExtra = 52                       ' Tabloid extra paper (11.69 in.by 18 in.).Dieser Wert ist PostScript-Treiber-spezifisch und wird ausschließlich von Linotronic-Druckern zur Senkung des Papierverbrauchs verwendet.
    A4Extra = 53                            ' A4 Extra (236 x 322 mm).Dieser Wert ist PostScript-Treiber-spezifisch und wird ausschließlich von Linotronic-Druckern zur Senkung des Papierverbrauchs verwendet.
    LetterTransverse = 54                   ' Letter transverse paper (8.275 in.by 11 in.).
    A4Transverse = 55                       ' A4 transverse paper (210 mm by 297 mm).
    LetterExtraTransverse = 56              ' Letter extra transverse paper (9.275 in.by 12 in.).
    APlus = 57                              ' SuperA/SuperA/A4 (227 x 356 mm).
    BPlus = 58                              ' SuperB/SuperB/A3 (305 x 487 mm).
    LetterPlus = 59                         ' Letter plus paper (8.5 in.by 12.69 in.).
    DIN_A4Plus = 60                         ' A4 Plus (210 x 330 mm).
    DIN_A5Transverse = 61                   ' A5 gedreht (148 x 210 mm).
    DIN_B5Transverse = 62                   ' B5 (JIS) gedreht (182 x 257 mm).
    DIN_A3Extra = 63                        ' A3 extra paper (322 mm by 445 mm).
    DIN_A5Extra = 64                        ' A5 Extra (174 x 235 mm).
    DIN_B5Extra = 65                        ' B5 (ISO) Extra (201 x 276 mm).
    DIN_A2 = 66                             ' A2 paper (420 mm by 594 mm).
    DIN_A3Transverse = 67                   ' A3 transverse paper (297 mm by 420 mm).
    A3ExtraTransverse = 68                  ' A3 Extra quer (322 x 445 mm).
    JapaneseDoublePostcard = 69             ' Japanische Doppelpostkarte (200 x 148 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    DIN_A6 = 70                             ' A6 (105 x 148 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    JapaneseEnvelopeKakuNumber2 = 71        ' Japanischer Umschlag Kaku #2.Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    JapaneseEnvelopeKakuNumber3 = 72        ' Japanischer Umschlag Kaku #3.Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    JapaneseEnvelopeChouNumber3 = 73        ' Japanischer Umschlag Chou #3.Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    JapaneseEnvelopeChouNumber4 = 74        ' Japanischer Umschlag Chou #4.Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    LetterRotated = 75                      ' Letter rotated paper (11 in.by 8.5 in.).
    DIN_A3Rotated = 76                      ' A3 gedreht (420 x 297 mm).
    DIN_A4Rotated = 77                      ' A4 gedreht (297 x 210 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    DIN_A5Rotated = 78                      ' A5 rotated paper (210 mm by 148 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    DIN_B4JisRotated = 79                   ' JIS B4 rotated paper (364 mm by 257 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    DIN_B5JisRotated = 80                   ' B5 (JIS) gedreht (257 x 182 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    JapanesePostcardRotated = 81            ' Japanische Postkarte gedreht (148 x 100 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    JapaneseDoublePostcardRotated = 82      ' Japanische Doppelpostkarte gedreht (148 x 200 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    DIN_A6Rotated = 83                      ' A6 gedreht (148 x 105 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    JapaneseEnvelopeKakuNumber2Rotated = 84 ' Japanischer Umschlag Kaku #2 gedreht.Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    JapaneseEnvelopeKakuNumber3Rotated = 85 ' Japanischer Umschlag Kaku #3 gedreht.Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    JapaneseEnvelopeChouNumber3Rotated = 86 ' Japanischer Umschlag Chou #3 gedreht.Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    JapaneseEnvelopeChouNumber4Rotated = 87 ' Japanischer Umschlag Chou #4 gedreht.Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    DIN_B6Jis = 88                          ' B6 (JIS) (128 x 182 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    DIN_B6JisRotated = 89                   ' B6 (JIS) gedreht (182 x 128 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Standard12x11 = 90                      ' Standard paper (12 in.by 11 in.).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    JapaneseEnvelopeYouNumber4 = 91         ' Japanischer Umschlag You #4.Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    JapaneseEnvelopeYouNumber4Rotated = 92  ' Japanischer Umschlag You #4 gedreht.Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Prc16K = 93                             ' Volksrepublik China 16K (146 x 215 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Prc32K = 94                             ' Volksrepublik China 32K (97 x 151 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Prc32KBig = 95                          ' Volksrepublik China 32K groß (97 x 151 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    PrcEnvelopeNumber1 = 96                 ' Volksrepublik China #1 Umschlag (102 x 165 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    PrcEnvelopeNumber2 = 97                 ' Volksrepublik China #2 Umschlag (102 x 176 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    PrcEnvelopeNumber3 = 98                 ' Volksrepublik China #3 Umschlag (125 x 176 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    PrcEnvelopeNumber4 = 99                 ' Volksrepublik China #4 Umschlag (110 x 208 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    PrcEnvelopeNumber5 = 100                ' Volksrepublik China #5 Umschlag (110 x 220 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    PrcEnvelopeNumber6 = 101                ' Volksrepublik China #6 Umschlag (120 x 230 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    PrcEnvelopeNumber7 = 102                ' Volksrepublik China #7 Umschlag (160 x 230 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    PrcEnvelopeNumber8 = 103                ' Volksrepublik China #8 Umschlag (120 x 309 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    PrcEnvelopeNumber9 = 104                ' Volksrepublik China #9 Umschlag (229 x 324 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    PrcEnvelopeNumber10 = 105               ' Volksrepublik China #10 Umschlag (324 x 458 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Prc16KRotated = 106                     ' Volksrepublik China 16K gedreht (146 x 215 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Prc32KRotated = 107                     ' Volksrepublik China 32K gedreht (97 x 151 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Prc32KBigRotated = 108                  ' Volksrepublik China 32K groß gedreht (97 x 151 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    PrcEnvelopeNumber1Rotated = 109         ' Volksrepublik China #1 Umschlag gedreht (165 x 102 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    PrcEnvelopeNumber2Rotated = 110         ' Volksrepublik China #2 Umschlag gedreht (176 x 102 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    PrcEnvelopeNumber3Rotated = 111         ' Volksrepublik China #3 Umschlag gedreht (176 x 125 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    PrcEnvelopeNumber4Rotated = 112         ' Volksrepublik China #4 Umschlag gedreht (208 x 110 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    PrcEnvelopeNumber5Rotated = 113         ' Volksrepublik China #5 Umschlag gedreht (220 x 110 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    PrcEnvelopeNumber6Rotated = 114         ' Volksrepublik China #6 Umschlag gedreht (230 x 120 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    PrcEnvelopeNumber7Rotated = 115         ' Volksrepublik China #7 Umschlag gedreht (230 x 160 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    PrcEnvelopeNumber8Rotated = 116         ' Volksrepublik China #8 Umschlag gedreht (309 x 120 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    PrcEnvelopeNumber9Rotated = 117         ' Volksrepublik China #9 Umschlag gedreht (324 x 229 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    PrcEnvelopeNumber10Rotated = 118        ' Volksrepublik China #10 Umschlag gedreht (458 x 324 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
End Enum

Public Function PaperKind_ToStr(e As PaperKind) As String
    Dim s As String
    Select Case e
    Case PaperKind.Custom:                             s = "Custom" '0                              ' Das Papierformat wird vom Benutzer festgelegt.
    Case PaperKind.Letter:                             s = "Letter" '1                              ' Letter paper (8.5 in.by 11 in.).
    Case PaperKind.LetterSmall:                        s = "LetterSmall" '2                         ' Letter small paper (8.5 in.by 11 in.).
    Case PaperKind.Tabloid:                            s = "Tabloid" '3                             ' Tabloid paper (11 in.by 17 in.).
    Case PaperKind.Ledger:                             s = "Ledger" '4                              ' Ledger paper (17 in.by 11 in.).
    Case PaperKind.Legal:                              s = "Legal" '5                               ' Legal paper (8.5 in.by 14 in.).
    Case PaperKind.Statement:                          s = "Statement" '6                           ' Statement paper (5.5 in.by 8.5 in.).
    Case PaperKind.Executive:                          s = "Executive" '7                           ' Executive paper (7.25 in.by 10.5 in.).
    Case PaperKind.DIN_A3:                             s = "DIN-A3" '8                              ' A3 paper (297 mm by 420 mm).
    Case PaperKind.DIN_A4:                             s = "DIN-A4" '9                              ' A4 (210 x 297 mm).
    Case PaperKind.DIN_A4Small:                        s = "DIN-A4Small" '10                        ' A4 klein (210 x 297 mm).
    Case PaperKind.DIN_A5:                             s = "DIN-A5" '11                             ' A5 (148 x 210 mm).
    Case PaperKind.DIN_B4:                             s = "DIN-B4" '12                             ' B4 (250 x 353 mm).
    Case PaperKind.DIN_B5:                             s = "DIN-B5" '13                             ' B5 (176 x 250 mm).
    Case PaperKind.Folio:                              s = "Folio" '14                              ' Folio paper (8.5 in.by 13 in.).
    Case PaperKind.Quarto:                             s = "Quarto" '15                             ' Quarto (215 x 275 mm).
    Case PaperKind.Standard10x14:                      s = "Standard10x14" '16                      ' Standard paper (10 in.by 14 in.).
    Case PaperKind.Standard11x17:                      s = "Standard11x17" '17                      ' Standard paper (11 in.by 17 in.).
    Case PaperKind.Note:                               s = "Note" '18                               ' Note paper (8.5 in.by 11 in.).
    Case PaperKind.Number9Envelope:                    s = "Number9Envelope" '19                    ' #9 envelope (3.875 in.by 8.875 in.).
    Case PaperKind.Number10Envelope:                   s = "Number10Envelope" '20                   ' #10 envelope (4.125 in.by 9.5 in.).
    Case PaperKind.Number11Envelope:                   s = "Number11Envelope" '21                   ' #11 envelope (4.5 in.by 10.375 in.).
    Case PaperKind.Number12Envelope:                   s = "Number12Envelope" '22                   ' #12 envelope (4.75 in.by 11 in.).
    Case PaperKind.Number14Envelope:                   s = "Number14Envelope" '23                   ' #14 envelope (5 in.by 11.5 in.).
    Case PaperKind.CSheet:                             s = "CSheet" '24                             ' C paper (17 in.by 22 in.).
    Case PaperKind.DSheet:                             s = "DSheet" '25                             ' D paper (22 in.by 34 in.).
    Case PaperKind.ESheet:                             s = "ESheet" '26                             ' E paper (34 in.by 44 in.).
    Case PaperKind.DLEnvelope:                         s = "DLEnvelope" '27                         ' Umschlag DL (110 x 220 mm).
    Case PaperKind.DIN_C5Envelope:                     s = "DIN-C5Envelope" '28                     ' Umschlag C5 (162 x 229 mm).
    Case PaperKind.DIN_C3Envelope:                     s = "DIN-C3Envelope" '29                     ' Umschlag C3 (324 x 458 mm).
    Case PaperKind.DIN_C4Envelope:                     s = "DIN-C4Envelope" '30                     ' Umschlag C4 (229 x 324 mm).
    Case PaperKind.DIN_C6Envelope:                     s = "DIN-C6Envelope" '31                     ' C6 envelope (114 mm by 162 mm).
    Case PaperKind.DIN_C65Envelope:                    s = "DIN-C65Envelope" '32                    ' C65 envelope (114 mm by 229 mm).
    Case PaperKind.DIN_B4Envelope:                     s = "DIN-B4Envelope" '33                     ' B4 (250 x 353 mm).
    Case PaperKind.DIN_B5Envelope:                     s = "DIN-B5Envelope" '34                     ' Umschlag B5 (176 x 250 mm).
    Case PaperKind.DIN_B6Envelope:                     s = "DIN-B6Envelope" '35                     ' Umschlag B6 (176 x 125 mm).
    Case PaperKind.ItalyEnvelope:                      s = "ItalyEnvelope" '36                      ' Umschlag Italien (110 x 230 mm).
    Case PaperKind.MonarchEnvelope:                    s = "MonarchEnvelope" '37                    ' Monarch envelope (3.875 in.by 7.5 in.).
    Case PaperKind.PersonalEnvelope:                   s = "PersonalEnvelope" '38                   ' 6 3/4 envelope (3.625 in.by 6.5 in.).
    Case PaperKind.USStandardFanfold:                  s = "USStandardFanfold" '39                  ' US standard fanfold (14.875 in.by 11 in.).
    Case PaperKind.GermanStandardFanfold:              s = "GermanStandardFanfold" '40              ' German standard fanfold (8.5 in.by 12 in.).
    Case PaperKind.GermanLegalFanfold:                 s = "GermanLegalFanfold" '41                 ' German legal fanfold (8.5 in.by 13 in.).
    Case PaperKind.DIN_IsoB4:                          s = "DIN-IsoB4" '42                          ' B4 (ISO) (250 x 353 mm).
    Case PaperKind.JapanesePostcard:                   s = "JapanesePostcard" '43                   ' Japanische Postkarte (100 x 148 mm).
    Case PaperKind.Standard9x11:                       s = "Standard9x11" '44                       ' Standard paper (9 in.by 11 in.).
    Case PaperKind.Standard10x11:                      s = "Standard10x11" '45                      ' Standard paper (10 in.by 11 in.).
    Case PaperKind.Standard15x11:                      s = "Standard15x11" '46                      ' Standard paper (15 in.by 11 in.).
    Case PaperKind.InviteEnvelope:                     s = "InviteEnvelope" '47                     ' Einladungsumschlag (220 x 220 mm).
    '48
    '49
    Case PaperKind.LetterExtra:                        s = "LetterExtra" '50                        ' Letter extra paper (9.275 in.by 12 in.).Dieser Wert ist PostScript-Treiber-spezifisch und wird ausschließlich von Linotronic-Druckern zur Senkung des Papierverbrauchs verwendet.
    Case PaperKind.LegalExtra:                         s = "LegalExtra" '51                         ' Legal extra paper (9.275 in.by 15 in.).Dieser Wert ist PostScript-Treiber-spezifisch und wird ausschließlich von Linotronic-Druckern zur Senkung des Papierverbrauchs verwendet.
    Case PaperKind.TabloidExtra:                       s = "TabloidExtra" '52                       ' Tabloid extra paper (11.69 in.by 18 in.).Dieser Wert ist PostScript-Treiber-spezifisch und wird ausschließlich von Linotronic-Druckern zur Senkung des Papierverbrauchs verwendet.
    Case PaperKind.DIN_A4Extra:                        s = "DIN_A4Extra" '53                        ' A4 Extra (236 x 322 mm).Dieser Wert ist PostScript-Treiber-spezifisch und wird ausschließlich von Linotronic-Druckern zur Senkung des Papierverbrauchs verwendet.
    Case PaperKind.LetterTransverse:                   s = "LetterTransverse" '54                   ' Letter transverse paper (8.275 in.by 11 in.).
    Case PaperKind.DIN_A4Transverse:                   s = "DIN_A4Transverse" '55                   ' A4 transverse paper (210 mm by 297 mm).
    Case PaperKind.LetterExtraTransverse:              s = "LetterExtraTransverse" '56              ' Letter extra transverse paper (9.275 in.by 12 in.).
    Case PaperKind.DIN_APlus:                          s = "DIN-APlus" '57                          ' SuperA/SuperA/A4 (227 x 356 mm).
    Case PaperKind.DIN_BPlus:                          s = "DIN-BPlus" '58                          ' SuperB/SuperB/A3 (305 x 487 mm).
    Case PaperKind.LetterPlus:                         s = "LetterPlus" '59                         ' Letter plus paper (8.5 in.by 12.69 in.).
    Case PaperKind.DIN_A4Plus:                         s = "DIN-A4Plus" '60                         ' A4 Plus (210 x 330 mm).
    Case PaperKind.DIN_A5Transverse:                   s = "DIN-A5Transverse" '61                   ' A5 gedreht (148 x 210 mm).
    Case PaperKind.DIN_B5Transverse:                   s = "DIN-B5Transverse" '62                   ' B5 (JIS) gedreht (182 x 257 mm).
    Case PaperKind.DIN_A3Extra:                        s = "DIN-A3Extra" '63                        ' A3 extra paper (322 mm by 445 mm).
    Case PaperKind.DIN_A5Extra:                        s = "DIN-A5Extra" '64                        ' A5 Extra (174 x 235 mm).
    Case PaperKind.DIN_B5Extra:                        s = "DIN-B5Extra" '65                        ' B5 (ISO) Extra (201 x 276 mm).
    Case PaperKind.DIN_A2:                             s = "DIN-A2" '66                             ' A2 paper (420 mm by 594 mm).
    Case PaperKind.DIN_A3Transverse:                   s = "DIN-A3Transverse" '67                   ' A3 transverse paper (297 mm by 420 mm).
    Case PaperKind.DIN_A3ExtraTransverse:              s = "DIN-A3ExtraTransverse" '68              ' A3 Extra quer (322 x 445 mm).
    Case PaperKind.JapaneseDoublePostcard:             s = "JapaneseDoublePostcard" '69             ' Japanische Doppelpostkarte (200 x 148 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Case PaperKind.DIN_A6:                             s = "DIN-A6" '70                             ' A6 (105 x 148 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Case PaperKind.JapaneseEnvelopeKakuNumber2:        s = "JapaneseEnvelopeKakuNumber2" '71        ' Japanischer Umschlag Kaku #2.Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Case PaperKind.JapaneseEnvelopeKakuNumber3:        s = "JapaneseEnvelopeKakuNumber3" '72        ' Japanischer Umschlag Kaku #3.Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Case PaperKind.JapaneseEnvelopeChouNumber3:        s = "JapaneseEnvelopeChouNumber3" '73        ' Japanischer Umschlag Chou #3.Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Case PaperKind.JapaneseEnvelopeChouNumber4:        s = "JapaneseEnvelopeChouNumber4" '74        ' Japanischer Umschlag Chou #4.Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Case PaperKind.LetterRotated:                      s = "LetterRotated" '75                      ' Letter rotated paper (11 in.by 8.5 in.).
    Case PaperKind.DIN_A3Rotated:                      s = "DIN-A3Rotated" '76                      ' A3 gedreht (420 x 297 mm).
    Case PaperKind.DIN_A4Rotated:                      s = "DIN-A4Rotated" '77                      ' A4 gedreht (297 x 210 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Case PaperKind.DIN_A5Rotated:                      s = "DIN-A5Rotated" '78                      ' A5 rotated paper (210 mm by 148 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Case PaperKind.DIN_B4JisRotated:                   s = "DIN-B4JisRotated" '79                   ' JIS B4 rotated paper (364 mm by 257 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Case PaperKind.DIN_B5JisRotated:                   s = "DIN-B5JisRotated" '80                   ' B5 (JIS) gedreht (257 x 182 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Case PaperKind.JapanesePostcardRotated:            s = "JapanesePostcardRotated" '81            ' Japanische Postkarte gedreht (148 x 100 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Case PaperKind.JapaneseDoublePostcardRotated:      s = "JapaneseDoublePostcardRotated" '82      ' Japanische Doppelpostkarte gedreht (148 x 200 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Case PaperKind.DIN_A6Rotated:                      s = "DIN-A6Rotated" '83                      ' A6 gedreht (148 x 105 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Case PaperKind.JapaneseEnvelopeKakuNumber2Rotated: s = "JapaneseEnvelopeKakuNumber2Rotated" '84 ' Japanischer Umschlag Kaku #2 gedreht.Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Case PaperKind.JapaneseEnvelopeKakuNumber3Rotated: s = "JapaneseEnvelopeKakuNumber3Rotated" '85 ' Japanischer Umschlag Kaku #3 gedreht.Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Case PaperKind.JapaneseEnvelopeChouNumber3Rotated: s = "JapaneseEnvelopeChouNumber3Rotated" '86 ' Japanischer Umschlag Chou #3 gedreht.Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Case PaperKind.JapaneseEnvelopeChouNumber4Rotated: s = "JapaneseEnvelopeChouNumber4Rotated" '87 ' Japanischer Umschlag Chou #4 gedreht.Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Case PaperKind.DIN_B6Jis:                          s = "DIN-B6Jis" '88                          ' B6 (JIS) (128 x 182 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Case PaperKind.DIN_B6JisRotated:                   s = "DIN-B6JisRotated" '89                   ' B6 (JIS) gedreht (182 x 128 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Case PaperKind.Standard12x11:                      s = "Standard12x11" '90                      ' Standard paper (12 in.by 11 in.).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Case PaperKind.JapaneseEnvelopeYouNumber4:         s = "JapaneseEnvelopeYouNumber4" '91         ' Japanischer Umschlag You #4.Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Case PaperKind.JapaneseEnvelopeYouNumber4Rotated:  s = "JapaneseEnvelopeYouNumber4Rotated" '92  ' Japanischer Umschlag You #4 gedreht.Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Case PaperKind.Prc16K:                             s = "Prc16K" '93                             ' Volksrepublik China 16K (146 x 215 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Case PaperKind.Prc32K:                             s = "Prc32K" '94                             ' Volksrepublik China 32K (97 x 151 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Case PaperKind.Prc32KBig:                          s = "Prc32KBig" '95                          ' Volksrepublik China 32K groß (97 x 151 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Case PaperKind.PrcEnvelopeNumber1:                 s = "PrcEnvelopeNumber1" '96                 ' Volksrepublik China #1 Umschlag (102 x 165 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Case PaperKind.PrcEnvelopeNumber2:                 s = "PrcEnvelopeNumber2" '97                 ' Volksrepublik China #2 Umschlag (102 x 176 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Case PaperKind.PrcEnvelopeNumber3:                 s = "PrcEnvelopeNumber3" '98                 ' Volksrepublik China #3 Umschlag (125 x 176 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Case PaperKind.PrcEnvelopeNumber4:                 s = "PrcEnvelopeNumber4" '99                 ' Volksrepublik China #4 Umschlag (110 x 208 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Case PaperKind.PrcEnvelopeNumber5:                 s = "PrcEnvelopeNumber5" '100                ' Volksrepublik China #5 Umschlag (110 x 220 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Case PaperKind.PrcEnvelopeNumber6:                 s = "PrcEnvelopeNumber6" '101                ' Volksrepublik China #6 Umschlag (120 x 230 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Case PaperKind.PrcEnvelopeNumber7:                 s = "PrcEnvelopeNumber7" '102                ' Volksrepublik China #7 Umschlag (160 x 230 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Case PaperKind.PrcEnvelopeNumber8:                 s = "PrcEnvelopeNumber8" '103                ' Volksrepublik China #8 Umschlag (120 x 309 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Case PaperKind.PrcEnvelopeNumber9:                 s = "PrcEnvelopeNumber9" '104                ' Volksrepublik China #9 Umschlag (229 x 324 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Case PaperKind.PrcEnvelopeNumber10:                s = "PrcEnvelopeNumber10"  '105              ' Volksrepublik China #10 Umschlag (324 x 458 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Case PaperKind.Prc16KRotated:                      s = "Prc16KRotated" '106                     ' Volksrepublik China 16K gedreht (146 x 215 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Case PaperKind.Prc32KRotated:                      s = "Prc32KRotated" '107                     ' Volksrepublik China 32K gedreht (97 x 151 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Case PaperKind.Prc32KBigRotated:                   s = "Prc32KBigRotated"         '108          ' Volksrepublik China 32K groß gedreht (97 x 151 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Case PaperKind.PrcEnvelopeNumber1Rotated:          s = "PrcEnvelopeNumber1Rotated" '109         ' Volksrepublik China #1 Umschlag gedreht (165 x 102 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Case PaperKind.PrcEnvelopeNumber2Rotated:          s = "PrcEnvelopeNumber2Rotated" '110         ' Volksrepublik China #2 Umschlag gedreht (176 x 102 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Case PaperKind.PrcEnvelopeNumber3Rotated:          s = "PrcEnvelopeNumber3Rotated" '111         ' Volksrepublik China #3 Umschlag gedreht (176 x 125 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Case PaperKind.PrcEnvelopeNumber4Rotated:          s = "PrcEnvelopeNumber4Rotated"  '112        ' Volksrepublik China #4 Umschlag gedreht (208 x 110 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Case PaperKind.PrcEnvelopeNumber5Rotated:          s = "PrcEnvelopeNumber5Rotated"  '113        ' Volksrepublik China #5 Umschlag gedreht (220 x 110 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Case PaperKind.PrcEnvelopeNumber6Rotated:          s = "PrcEnvelopeNumber6Rotated" '114         ' Volksrepublik China #6 Umschlag gedreht (230 x 120 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Case PaperKind.PrcEnvelopeNumber7Rotated:          s = "PrcEnvelopeNumber7Rotated" '115         ' Volksrepublik China #7 Umschlag gedreht (230 x 160 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Case PaperKind.PrcEnvelopeNumber8Rotated:          s = "PrcEnvelopeNumber8Rotated" '116         ' Volksrepublik China #8 Umschlag gedreht (309 x 120 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Case PaperKind.PrcEnvelopeNumber9Rotated:          s = "PrcEnvelopeNumber9Rotated" '117         ' Volksrepublik China #9 Umschlag gedreht (324 x 229 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    Case PaperKind.PrcEnvelopeNumber10Rotated:         s = "PrcEnvelopeNumber10Rotated" '118        ' Volksrepublik China #10 Umschlag gedreht (458 x 324 mm).Erfordert Windows 98, Windows NT 4.0 oder eine höhere Version.
    End Select
    PaperKind_ToStr = s
End Function

Public Function PaperKind_Parse(ByVal s As String) As PaperKind
    Dim e As PaperKind
    Select Case s
    Case "Custom":                            e = PaperKind.Custom
    Case "Letter":                            e = PaperKind.Letter
    Case "LetterSmall":                       e = PaperKind.LetterSmall
    Case "Tabloid":                           e = PaperKind.Tabloid
    Case "Ledger":                            e = PaperKind.Ledger
    Case "Legal":                             e = PaperKind.Legal
    Case "Statement":                         e = PaperKind.Statement
    Case "Executive":                         e = PaperKind.Executive
    Case "DIN-A3":                            e = PaperKind.DIN_A3
    Case "DIN-A4":                            e = PaperKind.DIN_A4
    Case "DIN-A4Small":                       e = PaperKind.DIN_A4Small
    Case "DIN-A5":                            e = PaperKind.DIN_A5
    Case "DIN-B4":                            e = PaperKind.DIN_B4
    Case "DIN-B5":                            e = PaperKind.DIN_B5
    Case "Folio":                             e = PaperKind.Folio
    Case "Quarto":                            e = PaperKind.Quarto
    Case "Standard10x14":                     e = PaperKind.Standard10x14
    Case "Standard11x17":                     e = PaperKind.Standard11x17
    Case "Note":                              e = PaperKind.Note
    Case "Number9Envelope":                   e = PaperKind.Number9Envelope
    Case "Number10Envelope":                  e = PaperKind.Number10Envelope
    Case "Number11Envelope":                  e = PaperKind.Number11Envelope
    Case "Number12Envelope":                  e = PaperKind.Number12Envelope
    Case "Number14Envelope":                  e = PaperKind.Number14Envelope
    Case "CSheet":                            e = PaperKind.CSheet
    Case "DSheet":                            e = PaperKind.DSheet
    Case "ESheet":                            e = PaperKind.ESheet
    Case "DLEnvelope":                        e = PaperKind.DLEnvelope
    Case "DIN-C5Envelope":                    e = PaperKind.DIN_C5Envelope
    Case "DIN-C3Envelope":                    e = PaperKind.DIN_C3Envelope
    Case "DIN-C4Envelope":                    e = PaperKind.DIN_C4Envelope
    Case "DIN-C6Envelope":                    e = PaperKind.DIN_C6Envelope
    Case "DIN-C65Envelope":                   e = PaperKind.DIN_C65Envelope
    Case "DIN-B4Envelope":                    e = PaperKind.DIN_B4Envelope
    Case "DIN-B5Envelope":                    e = PaperKind.DIN_B5Envelope
    Case "DIN-B6Envelope":                    e = PaperKind.DIN_B6Envelope
    Case "ItalyEnvelope":                     e = PaperKind.ItalyEnvelope
    Case "MonarchEnvelope":                   e = PaperKind.MonarchEnvelope
    Case "PersonalEnvelope":                  e = PaperKind.PersonalEnvelope
    Case "USStandardFanfold":                 e = PaperKind.USStandardFanfold
    Case "GermanStandardFanfold":             e = PaperKind.GermanStandardFanfold
    Case "GermanLegalFanfold":                e = PaperKind.GermanLegalFanfold
    Case "DIN-IsoB4":                         e = PaperKind.DIN_IsoB4
    Case "JapanesePostcard":                  e = PaperKind.JapanesePostcard
    Case "Standard9x11":                      e = PaperKind.Standard9x11
    Case "Standard10x11":                     e = PaperKind.Standard10x11
    Case "Standard15x11":                     e = PaperKind.Standard15x11
    Case "InviteEnvelope":                    e = PaperKind.InviteEnvelope
    '
    '
    Case "LetterExtra":                       e = PaperKind.LetterExtra
    Case "LegalExtra":                        e = PaperKind.LegalExtra
    Case "TabloidExtra":                      e = PaperKind.TabloidExtra
    Case "DIN_A4Extra":                       e = PaperKind.DIN_A4Extra
    Case "LetterTransverse":                  e = PaperKind.LetterTransverse
    Case "DIN_A4Transverse":                  e = PaperKind.DIN_A4Transverse
    Case "LetterExtraTransverse":             e = PaperKind.LetterExtraTransverse
    Case "DIN-APlus":                         e = PaperKind.DIN_APlus
    Case "DIN-BPlus":                         e = PaperKind.DIN_BPlus
    Case "LetterPlus":                        e = PaperKind.LetterPlus
    Case "DIN-A4Plus":                        e = PaperKind.DIN_A4Plus
    Case "DIN-A5Transverse":                  e = PaperKind.DIN_A5Transverse
    Case "DIN-B5Transverse":                  e = PaperKind.DIN_B5Transverse
    Case "DIN-A3Extra":                       e = PaperKind.DIN_A3Extra
    Case "DIN-A5Extra":                       e = PaperKind.DIN_A5Extra
    Case "DIN-B5Extra":                       e = PaperKind.DIN_B5Extra
    Case "DIN-A2":                            e = PaperKind.DIN_A2
    Case "DIN-A3Transverse":                  e = PaperKind.DIN_A3Transverse
    Case "DIN-A3ExtraTransverse":             e = PaperKind.DIN_A3ExtraTransverse
    Case "JapaneseDoublePostcard":            e = PaperKind.JapaneseDoublePostcard
    Case "DIN-A6":                            e = PaperKind.DIN_A6
    Case "JapaneseEnvelopeKakuNumber2":       e = PaperKind.JapaneseEnvelopeKakuNumber2
    Case "JapaneseEnvelopeKakuNumber3":       e = PaperKind.JapaneseEnvelopeKakuNumber3
    Case "JapaneseEnvelopeChouNumber3":       e = PaperKind.JapaneseEnvelopeChouNumber3
    Case "JapaneseEnvelopeChouNumber4":       e = PaperKind.JapaneseEnvelopeChouNumber4
    Case "LetterRotated":                     e = PaperKind.LetterRotated
    Case "DIN-A3Rotated":                     e = PaperKind.DIN_A3Rotated
    Case "DIN-A4Rotated":                     e = PaperKind.DIN_A4Rotated
    Case "DIN-A5Rotated":                     e = PaperKind.DIN_A5Rotated
    Case "DIN-B4JisRotated":                  e = PaperKind.DIN_B4JisRotated
    Case "DIN-B5JisRotated":                  e = PaperKind.DIN_B5JisRotated
    Case "JapanesePostcardRotated":           e = PaperKind.JapanesePostcardRotated
    Case "JapaneseDoublePostcardRotated":     e = PaperKind.JapaneseDoublePostcardRotated
    Case "DIN-A6Rotated":                     e = PaperKind.DIN_A6Rotated
    Case "JapaneseEnvelopeKakuNumber2Rotated": e = PaperKind.JapaneseEnvelopeKakuNumber2Rotated
    Case "JapaneseEnvelopeKakuNumber3Rotated": e = PaperKind.JapaneseEnvelopeKakuNumber3Rotated
    Case "JapaneseEnvelopeChouNumber3Rotated": e = PaperKind.JapaneseEnvelopeChouNumber3Rotated
    Case "JapaneseEnvelopeChouNumber4Rotated": e = PaperKind.JapaneseEnvelopeChouNumber4Rotated
    Case "DIN-B6Jis":                         e = PaperKind.DIN_B6Jis
    Case "DIN-B6JisRotated":                  e = PaperKind.DIN_B6JisRotated
    Case "Standard12x11":                     e = PaperKind.Standard12x11
    Case "JapaneseEnvelopeYouNumber4":        e = PaperKind.JapaneseEnvelopeYouNumber4
    Case "JapaneseEnvelopeYouNumber4Rotated": e = PaperKind.JapaneseEnvelopeYouNumber4Rotated
    Case "Prc16K":                            e = PaperKind.Prc16K
    Case "Prc32K":                            e = PaperKind.Prc32K
    Case "Prc32KBig":                         e = PaperKind.Prc32KBig
    Case "PrcEnvelopeNumber1":                e = PaperKind.PrcEnvelopeNumber1
    Case "PrcEnvelopeNumber2":                e = PaperKind.PrcEnvelopeNumber2
    Case "PrcEnvelopeNumber3":                e = PaperKind.PrcEnvelopeNumber3
    Case "PrcEnvelopeNumber4":                e = PaperKind.PrcEnvelopeNumber4
    Case "PrcEnvelopeNumber5":                e = PaperKind.PrcEnvelopeNumber5
    Case "PrcEnvelopeNumber6":                e = PaperKind.PrcEnvelopeNumber6
    Case "PrcEnvelopeNumber7":                e = PaperKind.PrcEnvelopeNumber7
    Case "PrcEnvelopeNumber8":                e = PaperKind.PrcEnvelopeNumber8
    Case "PrcEnvelopeNumber9":                e = PaperKind.PrcEnvelopeNumber9
    Case "PrcEnvelopeNumber10":               e = PaperKind.PrcEnvelopeNumber10
    Case "Prc16KRotated":                     e = PaperKind.Prc16KRotated
    Case "Prc32KRotated":                     e = PaperKind.Prc32KRotated
    Case "Prc32KBigRotated":                  e = PaperKind.Prc32KBigRotated
    Case "PrcEnvelopeNumber1Rotated":         e = PaperKind.PrcEnvelopeNumber1Rotated
    Case "PrcEnvelopeNumber2Rotated":         e = PaperKind.PrcEnvelopeNumber2Rotated
    Case "PrcEnvelopeNumber3Rotated":         e = PaperKind.PrcEnvelopeNumber3Rotated
    Case "PrcEnvelopeNumber4Rotated":         e = PaperKind.PrcEnvelopeNumber4Rotated
    Case "PrcEnvelopeNumber5Rotated":         e = PaperKind.PrcEnvelopeNumber5Rotated
    Case "PrcEnvelopeNumber6Rotated":         e = PaperKind.PrcEnvelopeNumber6Rotated
    Case "PrcEnvelopeNumber7Rotated":         e = PaperKind.PrcEnvelopeNumber7Rotated
    Case "PrcEnvelopeNumber8Rotated":         e = PaperKind.PrcEnvelopeNumber8Rotated
    Case "PrcEnvelopeNumber9Rotated":         e = PaperKind.PrcEnvelopeNumber9Rotated
    Case "PrcEnvelopeNumber10Rotated":        e = PaperKind.PrcEnvelopeNumber10Rotated
    End Select
    PaperKind_Parse = e
End Function

Public Sub PaperKind_ToListBox(aLBCB) 'aLBCB As ListBox Or As ComboBox
    aLBCB.Clear
    Dim i As Long, s As String
    For i = 0 To 140
        s = PaperKind_ToStr(i)
        If Len(s) Then aLBCB.AddItem s
    Next
End Sub
